### ISSUE TITLE
Once it returns false, it couldn't return true anymore

### ISSUE THREAD

**Issue by justinush** [LanceGin/jsotp#2]
If I try to verify a wrong OTP at the first try, then I try to verify the correct one, it returns me "false" result. What's wrong here?

**Comment by LanceGin** [comment]
Maybe you are using the TOTP? I think that's because when you try your "correct OTP" again, the "correct one" has been expired, you can use `TOTP.now()` to confirm the new OTP.

Also you can verify a expired OTP by giving the generation time of the OTP, for examle:
https://github.com/LanceGin/jsotp/blob/master/src/totp.js#L76

**Comment by justinush** [comment]
I even have generated the new TOTP every time I try. If the first try is correct, it works fine. But if the first is incorrect, it gives me wrong.

**Comment by justinush** [comment]
I use hi-base32 to encode my secret key.

**Comment by LanceGin** [comment]
I'm sorry for that I cannot reproduce your issue, I have tried that on my computer, but it works fine.

Here are the tests:

at first , I used my own module to generate a random b32 key:

![aaa](http://outub9z8v.bkt.clouddn.com/jsotp.png)

then I used `hi-base32` as you have mentioned to test it:

![aaa](http://outub9z8v.bkt.clouddn.com/jsotp.jpeg)

**Comment by justinush** [comment]
Hi, thanks for your quick reply, I'll check it out again tomorrow, thank you.

**Comment by justinush** [comment]
I have re-checked my program, there was a time-difference between my server (validator) and my client device (mobile app to generate new OTP). So, they produces a different result. Do you have any solution for my case?

**Comment by LanceGin** [comment]
@justinushermawan I think you should select the same timezone and correct the time on both of your server and client device.

**Comment by justinush** [comment]
Does the server counter has different start and end point with the client counter so they produce different result?

**Comment by LanceGin** [comment]
@justinushermawan TOTP has nothing with the counter, it only based on the time of your environment(server or client)

**Comment by justinush** [comment]
Oh, so we just need to synchronize server timezone with client e.g UTC?

**Comment by LanceGin** [comment]
@justinushermawan yes, that will solve your problem

**Comment by justinush** [comment]
Thanks @LanceGin , I'll close this issue.
