### ISSUE TITLE
npm version is Outdated

### ISSUE THREAD

**Issue by taichiyi** [LanceGin/jsotp#6]
Please update the npm version. The current version has many bugs.

**Comment by LanceGin** [comment]
a new version `1.0.4` has been published.

the type of the  `need-verify-otp instance` will be checked before verification.

please give more detail informations about `many bugs`.

**Comment by taichiyi** [comment]
V1.0.3 I found 2 bugs

V1.0.4 fixed those two bugs

No problem now.
